# Melfas MCS8000 Touchscreen controller drivers.
# 22 Nov 2011, JhoonKim, <mailto:jhoonkim@kttech.co.kr>

obj-$(CONFIG_KTTECH_TOUCH_MMS100)      += melfas_ts.o MMS100A_Config_Updater_V02.o MMS100A_Config_Updater_Customize.o
